#!/bin/bash
#PBS -N cv_uct 
#PBS -l nodes=1:ppn=1
#PBS -l walltime=45:30:00
#PBS -l mem=1GB 
#PBS -t 0-39
#PBS -j oe
#PBS -M zb9@nyu.edu
#PBS -m abe

player=${PBS_ARRAYID}
direc=$SCRATCH/Gomoku
BASE_DIR=$HOME/mnk
SRCDIR=$BASE_DIR/src
player=${PBS_ARRAYID}
agent=uctagent
data=model_input.csv
agent_file=$BASE_DIR/agents/$agent
test_data_file=$BASE_DIR/data/${data}SUB${player}test.csv
train_data_file=$BASE_DIR/data/${data}SUB${player}train.csv
result_path=$direc/${agent}_${data}_subject$player
fold_files=`find $BASE_DIR/data/ -name ${data}SUB${player}fold*`
number=0
module purge
module load matlab/2014a gcc/4.9.2
for test_fold in ${fold_files}
	do 
	test_data_file=${test_fold}
	train_data_file=$BASE_DIR/data/${data}SUB${player}_train_fold_${number}.csv
	result_path=$direc/${agent}_${data}_subject${player}_fold_${number}
	cd ${result_path}
	export MATLABPATH=$SRCDIR:$SRCDIR/matlab
	export LD_PRELOAD=$GCC_LIB/libstdc++.so
	echo "cross_validate($player,'$agent_file','$train_data_file','$test_data_file'); exit;" | matlab -nodisplay
	echo "Done"
	number=$((number+1))
	done

