#!/bin/python
# Generates a concrete uctagent file from the parameter file
#  ./script <test_results_file> 
#
#  (Ignores first and last lines in the result file)
# /scratch/zb9/Gomoku/uctagent_model_input.csv_subject1_fold_0/test_results1.dat
#
from sys import argv
from os import listdir
import re

def concrete(param_file):
	with open(param_file, 'r') as p:
		params=[x.strip() for x in p.readlines()]
		params[0] = param_file
		content= """ # UCT with fitting of the heuristic parameters
# automatically generated by {0}
implementation=UCT
prune_threshold={1}
gamma={2}
delta={3}
lapse_rate={4}
act_scale={5}
weights_0={6}
weights_1={7}
weights_2={8}
weights_3={9}
weights_4={10}
triangle_weight=0
policy_code=0
policy_lapse_rate=0
K0=0
exploration_constant={11}
virtual_rollouts=0
num_of_evals=1
vert_scale=1
diag_scale=1
opp_scale=1
"""
	conc=content.format(*params)
	return conc

files_file=argv[1]
with open(files_file,'r') as ff:
	for pf in ff:
		subject = re.search('subject(.+?)_',pf).group(1)
		fold = re.search('fold_(.+?)/',pf).group(1)
		name="uctagent_subject"+subject+"fold"+fold
		print "writing to"+ name
		conc=concrete(pf.strip())
		print conc
		with open(name,'w+') as cf:
			cf.write(conc)
		


