python scatter_switch.py time_pred0 ../data/37subjects.csvSUB0.csv > time_pred_avg_0.csv 
python scatter_switch.py time_pred1 ../data/37subjects.csvSUB1.csv > time_pred_avg_1.csv 
python scatter_switch.py time_pred2 ../data/37subjects.csvSUB2.csv > time_pred_avg_2.csv 
python scatter_switch.py time_pred3 ../data/37subjects.csvSUB3.csv > time_pred_avg_3.csv 
python scatter_switch.py time_pred4 ../data/37subjects.csvSUB4.csv > time_pred_avg_4.csv 
python scatter_switch.py time_pred5 ../data/37subjects.csvSUB5.csv > time_pred_avg_5.csv 
python scatter_switch.py time_pred6 ../data/37subjects.csvSUB6.csv > time_pred_avg_6.csv 
python scatter_switch.py time_pred7 ../data/37subjects.csvSUB7.csv > time_pred_avg_7.csv 
python scatter_switch.py time_pred8 ../data/37subjects.csvSUB8.csv > time_pred_avg_8.csv 
python scatter_switch.py time_pred9 ../data/37subjects.csvSUB9.csv > time_pred_avg_9.csv 
python scatter_switch.py time_pred10 ../data/37subjects.csvSUB10.csv > time_pred_avg_10.csv 
python scatter_switch.py time_pred11 ../data/37subjects.csvSUB11.csv > time_pred_avg_11.csv 
python scatter_switch.py time_pred12 ../data/37subjects.csvSUB12.csv > time_pred_avg_12.csv 
python scatter_switch.py time_pred13 ../data/37subjects.csvSUB13.csv > time_pred_avg_13.csv 
python scatter_switch.py time_pred14 ../data/37subjects.csvSUB14.csv > time_pred_avg_14.csv 
python scatter_switch.py time_pred15 ../data/37subjects.csvSUB15.csv > time_pred_avg_15.csv 
python scatter_switch.py time_pred16 ../data/37subjects.csvSUB16.csv > time_pred_avg_16.csv 
python scatter_switch.py time_pred17 ../data/37subjects.csvSUB17.csv > time_pred_avg_17.csv 
python scatter_switch.py time_pred18 ../data/37subjects.csvSUB18.csv > time_pred_avg_18.csv 
python scatter_switch.py time_pred19 ../data/37subjects.csvSUB19.csv > time_pred_avg_19.csv 
python scatter_switch.py time_pred20 ../data/37subjects.csvSUB20.csv > time_pred_avg_20.csv 
python scatter_switch.py time_pred21 ../data/37subjects.csvSUB21.csv > time_pred_avg_21.csv 
python scatter_switch.py time_pred22 ../data/37subjects.csvSUB22.csv > time_pred_avg_22.csv 
python scatter_switch.py time_pred23 ../data/37subjects.csvSUB23.csv > time_pred_avg_23.csv 
python scatter_switch.py time_pred24 ../data/37subjects.csvSUB24.csv > time_pred_avg_24.csv 
python scatter_switch.py time_pred25 ../data/37subjects.csvSUB25.csv > time_pred_avg_25.csv 
python scatter_switch.py time_pred26 ../data/37subjects.csvSUB26.csv > time_pred_avg_26.csv 
python scatter_switch.py time_pred27 ../data/37subjects.csvSUB27.csv > time_pred_avg_27.csv 
python scatter_switch.py time_pred28 ../data/37subjects.csvSUB28.csv > time_pred_avg_28.csv 
python scatter_switch.py time_pred29 ../data/37subjects.csvSUB29.csv > time_pred_avg_29.csv 
python scatter_switch.py time_pred30 ../data/37subjects.csvSUB30.csv > time_pred_avg_30.csv 
python scatter_switch.py time_pred31 ../data/37subjects.csvSUB31.csv > time_pred_avg_31.csv 
python scatter_switch.py time_pred32 ../data/37subjects.csvSUB32.csv > time_pred_avg_32.csv 
python scatter_switch.py time_pred33 ../data/37subjects.csvSUB33.csv > time_pred_avg_33.csv 
python scatter_switch.py time_pred34 ../data/37subjects.csvSUB34.csv > time_pred_avg_34.csv 
python scatter_switch.py time_pred35 ../data/37subjects.csvSUB35.csv > time_pred_avg_35.csv 
python scatter_switch.py time_pred36 ../data/37subjects.csvSUB36.csv > time_pred_avg_36.csv 
python scatter_switch.py time_pred37 ../data/37subjects.csvSUB37.csv > time_pred_avg_37.csv 
