f<-'time_pred_avg_0.csv'
source('time.R')
f<-'time_pred_avg_1.csv'
source('time.R')
f<-'time_pred_avg_10.csv'
source('time.R')
f<-'time_pred_avg_11.csv'
source('time.R')
f<-'time_pred_avg_12.csv'
source('time.R')
f<-'time_pred_avg_13.csv'
source('time.R')
f<-'time_pred_avg_14.csv'
source('time.R')
f<-'time_pred_avg_15.csv'
source('time.R')
f<-'time_pred_avg_16.csv'
source('time.R')
f<-'time_pred_avg_17.csv'
source('time.R')
f<-'time_pred_avg_18.csv'
source('time.R')
f<-'time_pred_avg_19.csv'
source('time.R')
f<-'time_pred_avg_2.csv'
source('time.R')
f<-'time_pred_avg_20.csv'
source('time.R')
f<-'time_pred_avg_21.csv'
source('time.R')
f<-'time_pred_avg_22.csv'
source('time.R')
f<-'time_pred_avg_23.csv'
source('time.R')
f<-'time_pred_avg_24.csv'
source('time.R')
f<-'time_pred_avg_25.csv'
source('time.R')
f<-'time_pred_avg_26.csv'
source('time.R')
f<-'time_pred_avg_27.csv'
source('time.R')
f<-'time_pred_avg_28.csv'
source('time.R')
f<-'time_pred_avg_29.csv'
source('time.R')
f<-'time_pred_avg_3.csv'
source('time.R')
f<-'time_pred_avg_30.csv'
source('time.R')
f<-'time_pred_avg_31.csv'
source('time.R')
f<-'time_pred_avg_32.csv'
source('time.R')
f<-'time_pred_avg_33.csv'
source('time.R')
f<-'time_pred_avg_34.csv'
source('time.R')
f<-'time_pred_avg_35.csv'
source('time.R')
f<-'time_pred_avg_36.csv'
source('time.R')
f<-'time_pred_avg_37.csv'
source('time.R')
f<-'time_pred_avg_4.csv'
source('time.R')
f<-'time_pred_avg_5.csv'
source('time.R')
f<-'time_pred_avg_6.csv'
source('time.R')
f<-'time_pred_avg_7.csv'
source('time.R')
f<-'time_pred_avg_8.csv'
source('time.R')
f<-'time_pred_avg_9.csv'
source('time.R')

