
d<-read.csv(f)
fit<-lm(d$rt ~ d$tree_switch + d$best_diff + d$entropy +d$max_val + d$norm_best_diff + d$num_consecutive + d$num_nodes)
sf=summary(fit)
png(paste(f, sep='','.png'))
par(mfrow=c(2,2),oma=c(0,0,2,0))
plot(d$best_diff, d$rt)
plot(d$tree_switch, d$rt)
plot(d$max_val, d$rt)
#text(20,20, paste('r2=' ,sf$r.squared))
print(paste('r2=' ,format(round(sf$r.squared, 2), nsmall = 2)))
title(paste('r2=' ,format(round(sf$r.squared, 2), nsmall = 2) ), outer=TRUE)
plot(d$entropy, d$rt)
dev.off()
